#!/usr/bin/env bash

export RUSTUP_TOOLCHAIN=nightly
export CARGO_HOME=$BUILD_PATH/cargo
export RUSTUP_HOME=$BUILD_PATH/cargo
export PATH=$CARGO_HOME/bin:$PATH
export MMTK_ROOT=$BUILD_PATH/tmp-mmtk

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- --default-toolchain "$RUSTUP_TOOLCHAIN" -y

source $CARGO_HOME/env
rustup toolchain install $RUSTUP_TOOLCHAIN

git clone https://github.com/wks/mmtk-core $MMTK_ROOT/mmtk-core
git clone --depth 1 https://github.com/mmtk/mmtk-ruby $MMTK_ROOT/mmtk-ruby

pushd $MMTK_ROOT/mmtk-core
git checkout ruby-friendly-tracing
popd

pushd $MMTK_ROOT/mmtk-ruby/mmtk
sed -i 's/^mmtk =/#mmtk =/g' Cargo.toml
echo \
    "mmtk = { path = \"../../mmtk-core\", features = [\"is_mmtk_object\"] }" \
    >> Cargo.toml

cargo +nightly build --release

install_package "openssl-1.1.1m" "https://www.openssl.org/source/openssl-1.1.1m.tar.gz#f89199be8b23ca45fc7cb9f1d8d3ee67312318286ad030f5316aca6462db6c96" mac_openssl --if has_broken_mac_openssl
CPPFLAGS=-DRUBY_DEBUG \
    CONFIGURE_OPTS=--with-mmtk-ruby=$MMTK_ROOT/mmtk-ruby \
    install_git "ruby-3.2-mmtk" "https://github.com/mmtk/ruby.git" "mmtk" ldflags_dirs autoconf standard_build standard_install_with_bundled_gems verify_openssl

